# Generated by Django 2.1.7 on 2022-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_url_id_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='track',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
